### ISSUE TITLE
Left trigger may get stuck, causing action to repeat multiple times

### ISSUE THREAD

**Issue by joshjcarrier** [joshjcarrier/minecontrol#27]

**Comment by joshjcarrier** [comment]
Should be fixed as part of the framework redesign.

**Comment by Pigna** [comment]
Bug still exists in latest version on your website. Also notice that not Left but the right button wont do anything.

Explained:
Left trigger place blocks. Right Break blocks (Right?)
But when right trigger nothing happens.
When left trigger place blocks happen and it starts breaking things. right after without stopping unless open menu or inventory.
Using Xbox one controller with http://update.joshjcarrier.com/minecontrol/ as my latest version download. (Its the v2)

Any chance you can fix this? :D would really appreciate it!
